defaults: &defaults
  host: 127.0.0.1
  options:
    raise_not_found_error: false
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: magichouse_dev
  sessions:
    default:
      database: magichouse_dev
      hosts:
        - 127.0.0.1:27017


test:
  <<: *defaults
  database: magichouse_test
  sessions:
    default:
      database: magichouse_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>